"""empty message

Revision ID: 47b9c9b266a4
Revises: fdc7a67313a5
Create Date: 2022-03-20 14:58:37.896917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b9c9b266a4'
down_revision = 'fdc7a67313a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'price')
    # ### end Alembic commands ###
